const TOGGLE_ACCOUNT_MODAL = 'TOGGLE_ACCOUNT_MODAL';
const TOGGLE_CALENDAR_MODAL = 'TOGGLE_CALENDAR_MODAL';
const RESET_TO_CURRENT_DATE = 'RESET_TO_CURRENT_DATE';
const TOGGLE_MONTH_LIST = 'TOGGLE_MONTH_LIST';
const CHANGE_MONTH = 'CHANGE_MONTH';
const TOGGLE_YEAR_LIST = 'TOGGLE_YEAR_LIST';
const CHANGE_YEAR = 'CHANGE_YEAR';
const PREV_MONTH = 'PREV_MONTH';
const NEXT_MONTH = 'NEXT_MONTH';
const SELECT_DATE = 'SELECT_DATE';
const PREV_DATE = 'PREV_DATE';
const NEXT_DATE = 'NEXT_DATE';

export {
  TOGGLE_ACCOUNT_MODAL,
  TOGGLE_CALENDAR_MODAL,
  RESET_TO_CURRENT_DATE,
  TOGGLE_MONTH_LIST,
  CHANGE_MONTH,
  TOGGLE_YEAR_LIST,
  CHANGE_YEAR,
  PREV_MONTH,
  NEXT_MONTH,
  SELECT_DATE,
  PREV_DATE,
  NEXT_DATE
}