const TOGGLE_ACCOUNT_MODAL = 'TOGGLE_ACCOUNT_MODAL';
const TOGGLE_CALENDAR_MODAL = 'TOGGLE_CALENDAR_MODAL';
const SET_TO_CURRENT_DATE = 'SET_TO_CURRENT_DATE';
const TOGGLE_MONTH_LIST = 'TOGGLE_MONTH_LIST';
const CHANGE_MONTH = 'CHANGE_MONTH';
const TOGGLE_YEAR_LIST = 'TOGGLE_YEAR_LIST';
const CHANGE_YEAR = 'CHANGE_YEAR';

export {
  TOGGLE_ACCOUNT_MODAL,
  TOGGLE_CALENDAR_MODAL,
  SET_TO_CURRENT_DATE,
  TOGGLE_MONTH_LIST,
  CHANGE_MONTH,
  TOGGLE_YEAR_LIST,
  CHANGE_YEAR
}