export const TOGGLE_ACCOUNT_MODAL = 'TOGGLE_ACCOUNT_MODAL';
export const TOGGLE_CALENDAR_MODAL = 'TOGGLE_CALENDAR_MODAL';
export const SET_TO_CURRENT_DATE = 'SET_TO_CURRENT_DATE';
export const TOGGLE_MONTH_LIST = 'TOGGLE_MONTH_LIST';
export const TOGGLE_YEAR_LIST = 'TOGGLE_YEAR_LIST';